pipeline {
    agent any

    stages {

        stage('Clone Repo') {
            steps {
                sh 'echo Cloning repo...'
                            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'echo Building image...'
                sh 'docker build -t slow-image slow-ci-cd-demo/'
            }
        }

        stage('Run Slow Script') {
            steps {
                sh 'chmod +x slow-ci-cd-demo/slow_script.sh'
                sh './slow-ci-cd-demo/slow_script.sh'
            }
        }

        stage('Final Slow Step') {
            steps {
                sh 'echo Final slow step...'
                sh ' echo Fast clone'
            }
        }
    }
}
