pipeline {
    agent any

    stages {

        stage('Clone') {
            steps {
                echo "Cloning repository..."
                sh 'sleep 5'
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "Building docker image..."
                dir('ci-cd-performance-fix') {
                    sh 'docker build -t slow-app .'
                }
            }
        }

        stage('Run App Tests') {
            steps {
                echo "Running tests..."
                sh 'sleep 10'
            }
        }

        stage('Final Step') {
            steps {
                sh 'sleep 15'
                echo "Done pipeline!"
            }
        }
    }
}
