pipeline {
    agent any
    
    environment {
        AWS_ACCESS_KEY_ID     = "AKIAQSARVEJAVP6NQVGV"
        AWS_SECRET_ACCESS_KEY = "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"
        AWS_DEFAULT_REGION    = 'ap-south-1'
    }

    stages {

        stage('Checkout Code') {
            steps {
                git 'https://github.com/joshidevesh7300/Project.git'
            }
        }

        stage('Build Lab Docker Image') {
            steps {
                sh 'docker build -t devops-lab devops-cloud-lab/docker'
            }
        }

        stage('Provision AWS Lab VM') {
            steps {
                dir('devops-cloud-lab/terraform') {
                    sh 'terraform init'
                    sh 'terraform apply -auto-approve'
                }
            }
        }
    }
}
