pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "🔨 Building Docker Image v1. ..."
                sh 'docker build -t flask-app:v1. -f app/Dockerfile ./app'
                sh 'docker tag flask-app:v1. flask-app:latest'
                echo "✅ Docker Image built successfully! (Tag: v1. & latest)"
            }
        }

        stage('Clean Old Images') {
            steps {
                echo "🧹 Cleaning old unused Docker images..."
                sh 'docker image prune -f'
            }
        }
    }
}
