
pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "Building Docker Image..."
                sh 'docker build -t flask-app:v1.0 -f app/Dockerfile ./app'
                echo "Docker Image built successfully!"
            }
        }
    }
}
